### ISSUE TITLE
[Feature Request] Support for modded liquids

### ISSUE THREAD

**Issue by JulianTompa** [RuochenFu21/CreateLiquidFuel#10]
Hello,
I am using the Create: Garnished Mod in conjunction with this mod and noticed that it is not possible to pump peanut oil into blaze burners.
Is there a way to make modded liquids compatible?

**Comment by furuochen-dev** [comment]
I do think I tried to add support, but I'll check why it didn't work

**Comment by JulianTompa** [comment]
I appreciate it, should you require any additional information I will try to provide them as quickly as possible

**Comment by furuochen-dev** [comment]
It's fine

**Comment by furuochen-dev** [comment]
Should already be fixed in v2.1.0
