### ISSUE TITLE
Crash on Forge 1.18.2

### ISSUE THREAD

**Issue by Polarite** [RuochenFu21/CreateLiquidFuel#2]
https://paste.tsundereunity.com/uhiyupizen.rb

Happens when imported fluid in the burners, extremely randomly happened on a friends burners, doesnt happen on ours.

**Comment by RuochenFu21** [comment]
weird

**Comment by Polarite** [comment]
![caged_grandma](https://github.com/RuochenFu21/CreateLiquidFuel/assets/34978332/db2aae55-cc89-4792-9b05-1cae83986258)
i release her once you fix this bug.

**Comment by Polarite** [comment]
I am sorry, she is too dangerous to be released, I will have to change the terms of our little deal. I will keep her in the cage. You still can push the fix tho.

**Comment by RuochenFu21** [comment]
Ok then! Fixed in 1.3!
