### ISSUE TITLE
Crashed on start up bug. error code 1 appeared

### ISSUE THREAD

**Issue by WilliamBlaze** [RuochenFu21/CreateLiquidFuel#4]
the name is self explaining as to the issue i'm experiencing with this mod in minecraft 1.20.1

https://pastebin.com/g6eZ5BRy <- the pastebin link has the full copy of "Latest.log" and the only thing i have as no crash long was recorded for the issue. just your basic "error code 1" message on the minecraft launcher screen when explaining the cause of the crash. All the mods used are all listed in the Pastebin link'

**Comment by furuochen-dev** [comment]
Fixed in 2.0.2
