### ISSUE TITLE
[1.18.2 Forge] Crash on startup "java.lang.reflect.InvocationTargetException"

### ISSUE THREAD

**Issue by V972** [RuochenFu21/CreateLiquidFuel#5]
Minecraft 1.18.2
Forge: 40.2.10
Create: 0.5.1.b
Liquid Fuel: 2.0.1

[Crash report](https://github.com/RuochenFu21/CreateLiquidFuel/files/12296350/crash-2023-08-09_00.50.53-fml.txt)

**Comment by furuochen-dev** [comment]
Unable to reproduce...

**Comment by furuochen-dev** [comment]
Maybe try update the forge version?

**Comment by V972** [comment]
> Maybe try update the forge version?

Can't really do that, that's the last 1.18 forge version

![image](https://github.com/RuochenFu21/CreateLiquidFuel/assets/45125685/1ea03507-9ee3-4722-b7a1-db749ce7c4db)

**Comment by V972** [comment]
I'll see what I can do, maybe it's a side-effect of another error.
