### ISSUE TITLE
failing to load correctly

### ISSUE THREAD

**Issue by BluberryPlay** [RuochenFu21/CreateLiquidFuel#6]
hi. Im getting an error, with create: liquid fuel loading. it is coming up as a **"java.lang.reflect.InvocationTargetException: null**
![image](https://github.com/RuochenFu21/CreateLiquidFuel/assets/142951198/0a8a6d97-f1a4-456d-8853-d8e1407df519)

is there any way you can solve this issue?

Versions :
Forge : **1.18.2 40.2.10**
Create : **1.18.2 0.5.1**
Liquid Fuel : **1.18.2 2.0.1**

My log if this is needed ::
[latest.log](https://github.com/RuochenFu21/CreateLiquidFuel/files/12498061/latest.log)

**Comment by furuochen-dev** [comment]
It does not look like a problem with this mod

**Comment by furuochen-dev** [comment]
It looks like some shader/Moonlight Lib problem

**Comment by BluberryPlay** [comment]
oh? how would I fix this issue then?
Ive never had this problem before.

**Comment by furuochen-dev** [comment]
I'm not sure, but you should report to Moonlight Lib maybe

**Comment by furuochen-dev** [comment]
They might be able to help you

**Comment by BluberryPlay** [comment]
okay thanks!
