### ISSUE TITLE
Refmap is missing

### ISSUE THREAD

**Issue by Xyphenore** [RuochenFu21/CreateLiquidFuel#8]
### Describe the Bug

The refmap is missing.

The warning printed:
'Reference map 'CreateLiquidFuel.refmap.json' for createliquidfuel.mixins.json could not be read. If this is a development environment you can ignore this message'

### Reproduction Steps

1. Install the mod.
2. Run the game with the output console.
3. Warning is printed on console.

### Expected Result

No warning.

### Versions:

- Create: 0.5.1d
- Forge: 47.1.47
- CreateLiquidFuel: 2.0.2
- Minecraft: 1.20.1

**Comment by furuochen-dev** [comment]
Does the game crash? Warnings are fine

**Comment by Xyphenore** [comment]
The game works good.

**Comment by furuochen-dev** [comment]
Does't sound like a problem

**Comment by furuochen-dev** [comment]
Thanks for reporting tho
